
title: The Westchester NY Baha'i Communities
desctiption: Public website for Westchester Baha'i Cluster. Theme forked from Karna, a responsive jekyll theme which includes pinterest like pins.
url: https://westchesterbahai.github.io/westchesterbahai/
permalink: ':title/'

markdown: kramdown
#remote-theme: sharu725/karna
#full-version: "http://webjeda.com/karna-full/"

sass:
    style: compressed

  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge

collections:
  devotionals:
    output: true
  development:
    output: true
  childrens-class:
    output: true
  youth-group:
    output: true
  study-circle:
    output: true
  special-events:
    output: true
  bahai-meeting:
    output: true

# Tracker
analytics: UA-83979019-1

# Comments
#disqus-shortname: webjeda-demo

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]
version: 0.8

plugins_dir: 
    - jekyll-paginate
    - jekyll-seo-tag
